### ISSUE TITLE
Release 1.1.1 Checklist

### ISSUE THREAD

**Issue by tajmone** [tajmone/polygen-docs#31]
Last-minute checlikst before merging into `master` the `dev1.1.1` branch and creating the `1.1.1` release:

- [x] polish/squash commits in `dev1.1.1` branch to leave behind a clean history.
- [x] Double-check the CHANGELOGs. (see #34)
- [x] Check/fix PML sources:
    + [x] Remove `-rc` from version (`1.1.1-rc` &rarr; `1.1.1-rc`):
        * [x] PML EN
        * [x] PML IT
    + [x] Edition date must match day of release (today):
        * [x] PML EN
        * [x] PML IT
    + [x] Update CHANGELOG (PP comment block) at source end:
        * [x] PML EN
        * [x] PML IT
    + [x] Rebuild both documents.
    + [x] Copy them (_again_) to root folder (replacing current releases):
        * [x] PML EN
        * [x] PML IT
    + [x] Copy them to `archived/` folder:
        * [x] `polygen-spec_EN_1_1_1.html`
        * [x] `polygen-spec_IT_1_1_1.html`
        * [x] Update `archived/README.md`
- [x] Update `README.md`:
    + [x] Update release badge to `1.1.1`.
- [x] ~~Merge~~ Squash `dev1.1.1` into `master`.
- [x] Create the `1.1.1` release.
